---
- name: Create VLANs and SVIs in NX-OS
  hosts: leafs
  gather_facts: no
  vars:
    vlans:
      - { name: uSeg_ZoneA, id: '2010', vni: '32010', primary: native }
      - { name: uSeg_ZoneB, id: '2020', vni: '32020', primary: 'yes', associates: '2021-2022' }
      - { name: uSeg_Web1, id: '2021', vni: '32021', primary: 'no', type: community }
      - { name: uSeg_Web2, id: '2022', vni: '32022', primary: 'no', type: community }
      - { name: uSeg_ZoneC, id: '2030', vni: '32030', primary: 'yes', associates: '2031' }
      - { name: uSeg_DB1, id: '2031', vni: '32031', primary: 'no', type: isolated }
    svis:
      - { name: "vlan2010", ip: 192.168.10.1/24, vrf: devlit-4001 }
      - { name: "vlan2020", ip: 192.168.20.1/24, vrf: devlit-4001 }
      - { name: "vlan2030", ip: 192.168.30.1/24, vrf: devlit-4001 }

  tasks:
  - name: "Enable Private VLAN Feature"
    nxos_feature:
      feature: private-vlan
      state: enabled
  
  - name: "Create VLANs"
    nxos_vlans:
      config:
        - vlan_id: "{{ item.id }}"
          name: "{{ item.name }}"
          mapped_vni: "{{ item.vni }}"
          enabled: 'yes'
    loop:
      - { name: uSeg_ZoneA, id: '2010', vni: '32010' }
      - { name: uSeg_ZoneB, id: '2020', vni: '32020' }
      - { name: uSeg_Web1, id: '2021', vni: '32021' }
      - { name: uSeg_Web2, id: '2022', vni: '32022' }
      - { name: uSeg_ZoneC, id: '2030', vni: '32030' }
      - { name: uSeg_DB1, id: '2031', vni: '32031' }

  - name: "Configure Primary VLANs"
    nxos_config:
      lines:
        - private-vlan primary
        - private-vlan association {{ item.assoc }}
      parents: vlan {{ item.id }}
    loop:
      - { id: '2020', assoc: '2021-2022' }
      - { id: '2030', assoc: '2031' }

  - name: "Configure Secondary VLANs"
    nxos_config:
      lines:
        - private-vlan {{ item.type }}
      parents: vlan {{ item.id }}
    loop:
      - { id: '2021', type: 'community' }
      - { id: '2022', type: 'community' }
      - { id: '2031', type: 'isolated' }

  - name: "Create SVI Interfaces"
    nxos_interfaces:
      config:
        - name: "{{ item.name }}"
          enabled: yes
    loop: "{{ svis }}"

  - name: "Assign VRF to SVI Interfaces"
    nxos_vrf_interface:
      interface: "{{ item.name }}"
      vrf: "{{ item.vrf }}"
    loop: "{{ svis }}"

  - name: "Create Native SVIs"
    nxos_l3_interfaces:
      config:
        - name: "{{ item.name }}"
          ipv4:
            - address: "{{ item.ip }}"
    loop: "{{ svis }}"

  - name: "Config Primary SVIs"
    nxos_config:
      lines:
        - fabric forwarding mode anycast-gateway
        - private-vlan mapping {{ item.assoc }}
      parents: interface vlan {{ vlan.id }}
    loop:
      - { id: '2020', assoc: '2021-2022' }
      - { id: '2030', assoc: '2031' }
